RestaurantApp/Models/Cuisine.cs
using System;

using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;

using System.Linq;

using System.Web;

 

namespace RestaurantApp.Models

{

    public class Cuisine

    {

        [Key]

        public int id { get; set; }

        public string name { get; set; }



        public string nutritionInfo { get; set; }



        public string texture { get; set; }



        public ICollection<RestaurantInfo> RestaurantInfos { get; set; }

    }

}

RestaurantApp/Models/MenuItemType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RestaurantApp.Models
{
    public class MenuItemType
    {
        [Key]
        public int Id { get; set; }
        public string Type { get; set; }

        [ForeignKey("RestaurantInfo")]
        public int RestaurantId { get; set; }
        public RestaurantInfo RestaurantInfo { get; set; }

        public string Description { get; set; }
        public decimal Price { get; set; }
    }
}

RestaurantApp/Models/RestaurantInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RestaurantApp.Models
{
    public class RestaurantInfo
    {
        [Key]
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string phone { get; set; }
        public string website { get; set; }

        [ForeignKey("Cuisine")]
        public int CuisineId { get; set; }
        public Cuisine Cuisine { get; set; }
        public string rating { get; set; }
        public string pricerange { get; set; }

        

    }
}

RestaurantApp/Models/RestaurantMenu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RestaurantApp.Models
{
    public class RestaurantMenu
    {
        [Key, Column(Order = 0)]
        public int Id { get; set; }

        [Key, Column(Order = 1)]
        public string MenuItem { get; set; }

        public string Description { get; set; }
        public decimal Price { get; set; }

        [ForeignKey("RestaurantInfo")]
        public int RestaurantId { get; set; }
        public RestaurantInfo RestaurantInfo { get; set; }
    }
  
}

RestaurantApp/Models/Zipcode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestaurantApp.Models
{
    public class Zipcode
    {
        [Key]
        public int zipcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}

RestaurantApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RestaurantApp/Controllers/RestaurantController.cs
using RestaurantApp.Models;
using RestaurantApp.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace RestaurantApp.Controllers
{
    public class RestaurantController : Controller
    {



        public ActionResult GetAllRestaurants()
        {



            RestaurantRepo restaurantRepo = new RestaurantRepo();
            ModelState.Clear();
            return View(restaurantRepo.GetAllRestaurants());
        }
        // GET: Restaurant
        public ActionResult Index()
        {
            return View();
        }



        // GET: Restaurant/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }



        // GET: Restaurant/Create
        public ActionResult AddRestaurantInfo()
        {
            return View();
        }



        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult AddRestaurantInfo(RestaurantInfo restaurantInfo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RestaurantRepo restaurantRepo = new RestaurantRepo();



                    if (restaurantRepo.AddRestaurantInfo(restaurantInfo))
                    {
                        ViewBag.Message = "Restaurant details added successfully";

                    }
                }
                //return RedirectToAction("GetAllRestaurants");
                return View();
            }
            catch (Exception ex)
            {



                return View();
            }
        }



        public ActionResult AddCuisine()
        {
            return View();
        }



        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult AddCuisine(Cuisine cuisine)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RestaurantRepo restaurantRepo = new RestaurantRepo();



                    if (restaurantRepo.AddCuisine(cuisine))
                    {
                        ViewBag.Message = "Restaurant details added successfully";
                    }
                }



                return View();
            }
            catch (Exception ex)
            {



                return View();
            }
        }



        public ActionResult AddRestaurantMenu()
        {
            return View();
        }



        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult AddRestaurantMenu(RestaurantMenu restaurantMenu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RestaurantRepo restaurantRepo = new RestaurantRepo();



                    if (restaurantRepo.AddRestaurantMenu(restaurantMenu))
                    {
                        ViewBag.Message = "RestaurantMenu details added successfully";
                    }
                }



                return View();
            }
            catch (Exception ex)
            {



                return View();
            }
        }



        public ActionResult AddMenuItemType()
        {
            return View();
        }



        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult AddMenuItemType(MenuItemType menuItemType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RestaurantRepo restaurantRepo = new RestaurantRepo();



                    if (restaurantRepo.AddMenuItemType(menuItemType))
                    {
                        ViewBag.Message = "MenuItemType details added successfully";
                    }
                }



                return View();
            }
            catch (Exception ex)
            {



                return View();
            }
        }



        // GET: Restaurant/Edit/5
        public ActionResult EditRestaurantInfo(int id)
        {
            RestaurantRepo restaurantRepo = new RestaurantRepo();
            return View(restaurantRepo.GetAllRestaurants().Find(restaurant => restaurant.id == id));

        }



        // POST: Restaurant/Edit/5
        [HttpPost]
        public ActionResult EditRestaurantInfo(int id, RestaurantInfo restaurantInfo)
        {
            try
            {
                // TODO: Add update logic here



                RestaurantRepo restaurantRepo = new RestaurantRepo();
                restaurantRepo.UpdateRestaurantInfo(restaurantInfo);
                return View();
            }
            catch (Exception ex)
            {



                return View();
            }
        }



        // GET: Restaurant/Delete/5
        public ActionResult DeleteRestaurantInfo(int id, RestaurantInfo restaurantInfo)
        {
            RestaurantRepo restaurantRepo = new RestaurantRepo();
            //return View(restaurantRepo.GetAllRestaurants().Find(restaurant => restaurant.id == id));
            if (restaurantRepo.DeleteRestaurantInfo(restaurantInfo))
            {
                ViewBag.AlertMsg = "RestaurantInfo details deleted successfully";



            }
            return RedirectToAction("GetAllRestaurants");



        }




    }
}

RestaurantApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RestaurantApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Group 3 - Restaurant CRUD<br />
    Wichita State University, Kansas<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RestaurantApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RestaurantApp/Views/Restaurant/AddCuisine.cshtml
@model RestaurantApp.Models.Cuisine


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cuisine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
            <br />
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
            <br />
            @Html.LabelFor(model => model.nutritionInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nutritionInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nutritionInfo, "", new { @class = "text-danger" })
            </div>
            <br />
            @Html.LabelFor(model => model.texture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.texture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.texture, "", new { @class = "text-danger" })
            </div>
            <br />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantApp/Views/Restaurant/AddRestaurantInfo.cshtml
@model RestaurantApp.Models.RestaurantInfo


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RestaurantInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuisineId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CuisineId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CuisineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pricerange, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pricerange, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pricerange, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Message

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllRestaurants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js");
}

RestaurantApp/Views/Restaurant/DeleteRestaurantInfo.cshtml
@model RestaurantApp.Models.RestaurantInfo

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RestaurantInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CuisineId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CuisineId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pricerange)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pricerange)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "GetAllRestaurants")
        </div>
    }
</div>

RestaurantApp/Views/Restaurant/EditRestaurantInfo.cshtml
@model RestaurantApp.Models.RestaurantInfo


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RestaurantInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CuisineId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CuisineId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CuisineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pricerange, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.pricerange, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pricerange, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllRestaurants", new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantApp/Views/Restaurant/GetAllRestaurants.cshtml
@model IEnumerable<RestaurantApp.Models.RestaurantInfo>
<br />
<div>

    @Html.ActionLink("AddRestaurant", "AddRestaurantInfo", new { @class = "btn btn-danger" })

</div>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.zipcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.website)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CuisineId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pricerange)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.website)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CuisineId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pricerange)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditRestaurantInfo", new { id = item.id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "DeleteRestaurantInfo", new { id = item.id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

RestaurantApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Restaurant DB", "AddRestaurantInfo", "Restaurant", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Restaurant", "AddRestaurantInfo", "Restaurant")</li>

                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>